### PR TITLE
src/shutdown-dialog.vala: Rephrase shutdown dialog's new timeout mess…

### PR DESCRIPTION
**Pull request by sunweaver**
…age(s) slightly.

### CODE REVIEW

**Review by Ionic — APPROVED** [review]
LGTM.

**Comment by sunweaver** [comment]
> LGTM.

Then please do a signed merged. Thx.

**Comment by Ionic** [comment]
I tried to, but was denied, because the branch is protected and I'm not an admin. See IRC.

**Comment by Ionic** [comment]
Merged via 4af2208125ece598f69859ede8a79c0a9ed5705e.

**Pull request closed without merging**
