### PR TITLE
Bring back multi-seat support

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@Ionic Can I have your opinion on this?

@tari01 Yours, as well?

Thanks!

**Comment by ghost** [comment]
I haven't actually set up a multiseat testing environment, but the code changes look sound.

**Comment by sunweaver** [comment]
@Ionic @tari01 can you revisit this MR? If you are not experienced with multi-seat setup, please review it with one greeter session in mind. The multi-seat fix is sufficiently addressed by launching the greeter via dbus-run-session and sub-launching the indicators in the same environment.

**Review by ghost — APPROVED** [review]
Works as advertised!

I had an issue, however. When building from source, it detected GTK4
https://github.com/ArcticaProject/arctica-greeter/blob/b35978fb83d205435b6278c0f8c8891be99bc40a/configure.ac#L99
set HAVE_GTK_4_0 and Vala started to use ifdeffed GTK4 code portions. I had to remove the above check to make it succeed. 

Do we have a bug here, or is it just my build?

**Comment by Ionic** [comment]
That's #56, yeah.

**Comment by sunweaver** [comment]
> Works as advertised!
> 
> I had an issue, however. When building from source, it detected GTK4
> 
> https://github.com/ArcticaProject/arctica-greeter/blob/b35978fb83d205435b6278c0f8c8891be99bc40a/configure.ac#L99
> 
> 
> set HAVE_GTK_4_0 and Vala started to use ifdeffed GTK4 code portions. I had to remove the above check to make it succeed.
> Do we have a bug here, or is it just my build?

Simply remove GTK-4 dev:pkgs for now. We need to enforce the build variant via a configure option. Assigned to @Ionic, iirc.

**Pull request merged**
